apiVersion: v1
kind: Service
metadata:
  name: {{ template "duckula.fullname" . }}
  labels:
    app: {{ template "duckula.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ops
    port: {{ .Values.service.port }}
  selector:
    app: {{ template "duckula.name" . }}
    component: ops
    