image: registry.cn-shanghai.aliyuncs.com/rjzjh/duckula
imageOpsTag: ops.2.3.0
imageDataTag: data.2.3.0
imagePullPolicy: IfNotPresent
env:
  zk: docker.for.win.localhost:2181
  rootpath: /duckula2
service:
  type: ClusterIP
  port: 8080
  # nodePort: 32000
#持久化 
persistence:
  enabled: false
  # 指定存储，推荐使用此方式，注意创建的的访问模式为：accessMode: ReadWriteMany
  #existingClaim: duckula-test-duckula-data
  # 快速搭建demo可以使用此方式，要求k8s拥有此storageClass
  storageClass: xforcecloud-disk-share
  accessMode: ReadWriteMany
  size: 40Gi
  annotations: {}
  
userconfig:
  root:

podAnnotations: {}

resources:
  requests:
    memory: 1024Mi
    cpu: 200m
  limits:
    memory: 1280Mi
    cpu: 200m
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
#hosts:
#- {ip: 192.168.11.61, host: [zk-kafka-01]}